### ISSUE TITLE
Rearchitect the application to API-first

### ISSUE THREAD

**Issue by jfversluis** [CfpExchange/CfpExchange#110]
I think it's a good idea to separate the front-end from the back-end and create an API-first solution. This enables us to easily connect more solutions, i.e. an app to the backend.

Things to keep in mind:

- Endpoint versioning
- Authentication/authorization. I wouldn't even mind sharing our data with others, as long as we have some control
- ???

**Comment by rickvdbosch** [comment]
For this to be able to work, we need to first extract as much logic from the frontend as we can. This way, we can reuse what we have already to implement the API's (if we want to keep the backend in C#).

With PR #117 there's already quite some refactoring done. Next issue to work on to facilitate this one would be #115, so that we can eventually do #116 . Then we should be good to go 😁

**Comment by Jandev** [comment]
> I think it's a good idea to separate the front-end from the back-end and create an API-first solution. This enables us to easily connect more solutions, i.e. an app to the backend.

Sounds like Azure API Management, right?
You get all of this stuff out of the box. We could even create the alpha/beta endpoints already with the current API, but I kind of agree with @rickvdbosch. 
Making the API mature with all of the logic should be step 1 and then expose it via something like APIM. 
I hope the Consumption model will suffice, otherwise we might need to set you up some sponsor/donate site for you.

**Comment by jfversluis** [comment]
All great suggestions! I was thinking to at least setup the GH Sponsoring for this thing. Not that I expect anything from it, and definitely not something I'm expecting in return at all, but everything and anything that comes in will be a nice support :) 

First thing is merged, we now have a separated API thanks to the great efforts of Rick!

I like the idea of also having beta endpoints etc.

**Comment by rickvdbosch** [comment]
Quick question on this one: if we're completely moving to an API first approach, will we replace the ASP.NET frontend with a SPA based one? And if so, what framework will we use?

**Comment by jfversluis** [comment]
I guess that would be cool. It's been a long time though since I have been using things like that. So what are the cool young people using these days?

**Comment by rickvdbosch** [comment]
I might not be the right person to ask ... 👴🏻
React, Angular and Vue are the _big three_ at this point and have been for quite some time now. As far as I'm concerned, Angular might be a 'bit much' because of its complexity.
I've done quite a few Angular apps, but I'm open to do Vue or React as well. Might be smart to ask @Jandev to see if he has any knowledge or preference?
